import 'package:flutter/material.dart';

void main() {
  runApp(const KudakeIranApp());
  }

  class KudakeIranApp extends StatelessWidget {
    const KudakeIranApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  debugShowCheckedModeBanner: false,
                        title: 'KudakeIran',
                              theme: ThemeData(
                                      primarySwatch: Colors.indigo,
                                              useMaterial3: true,
                                                    ),
                                                          home: const SplashPage(),
                                                              );
                                                                }
                                                                }

                                                                // --- SPLASH PAGE ---
                                                                class SplashPage extends StatefulWidget {
                                                                  const SplashPage({super.key});

                                                                    @override
                                                                      State<SplashPage> createState() => _SplashPageState();
                                                                      }

                                                                      class _SplashPageState extends State<SplashPage> {
                                                                        @override
                                                                          void initState() {
                                                                              super.initState();
                                                                                  Future.delayed(const Duration(seconds: 3), () {
                                                                                        Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => const OnboardingPage()));
                                                                                            });
                                                                                              }

                                                                                                @override
                                                                                                  Widget build(BuildContext context) {
                                                                                                      return const Scaffold(
                                                                                                            backgroundColor: Color(0xFF6C63FF),
                                                                                                                  body: Center(
                                                                                                                          child: Text(
                                                                                                                                    "KudakeIran",
                                                                                                                                              style: TextStyle(fontSize: 32, color: Colors.white, fontWeight: FontWeight.bold),
                                                                                                                                                      ),
                                                                                                                                                            ),
                                                                                                                                                                );
                                                                                                                                                                  }
                                                                                                                                                                  }

                                                                                                                                                                  // --- ONBOARDING PAGE ---
                                                                                                                                                                  class OnboardingPage extends StatelessWidget {
                                                                                                                                                                    const OnboardingPage({super.key});

                                                                                                                                                                      @override
                                                                                                                                                                        Widget build(BuildContext context) {
                                                                                                                                                                            return Scaffold(
                                                                                                                                                                                  body: Padding(
                                                                                                                                                                                          padding: const EdgeInsets.all(24.0),
                                                                                                                                                                                                  child: Column(
                                                                                                                                                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                      children: [
                                                                                                                                                                                                                                  const Text("به اپلیکیشن کودک ایران خوش آمدید", textAlign: TextAlign.center, style: TextStyle(fontSize: 24)),
                                                                                                                                                                                                                                              const SizedBox(height: 30),
                                                                                                                                                                                                                                                          ElevatedButton(
                                                                                                                                                                                                                                                                        onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (context) => const KidHomePage())),
                                                                                                                                                                                                                                                                                      child: const Text("ورود به بخش کودک"),
                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                              TextButton(
                                                                                                                                                                                                                                                                                                                            onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (context) => const ParentDashboard())),
                                                                                                                                                                                                                                                                                                                                          child: const Text("پنل والدین"),
                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                    // --- KID HOME PAGE ---
                                                                                                                                                                                                                                                                                                                                                                                    class KidHomePage extends StatelessWidget {
                                                                                                                                                                                                                                                                                                                                                                                      const KidHomePage({super.key});

                                                                                                                                                                                                                                                                                                                                                                                        @override
                                                                                                                                                                                                                                                                                                                                                                                          Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                              return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                    appBar: AppBar(title: const Text("دنیای کودک")),
                                                                                                                                                                                                                                                                                                                                                                                                          body: GridView.count(
                                                                                                                                                                                                                                                                                                                                                                                                                  padding: const EdgeInsets.all(20),
                                                                                                                                                                                                                                                                                                                                                                                                                          crossAxisCount: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                  children: ["آموزش", "بازی", "نقاشی", "جایزه"].map((title) => Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                            color: Colors.orangeAccent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: Center(child: Text(title, style: const TextStyle(color: Colors.white, fontSize: 20))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                              )).toList(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // --- PARENT DASHBOARD ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          class ParentDashboard extends StatelessWidget {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const ParentDashboard({super.key});

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          appBar: AppBar(title: const Text("پنل والدین")),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: const Center(child: Text("گزارش پیشرفت فرزند شما")),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }