name: Final Ultimate Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK in Clean Environment
        run: |
          # ۱. ساخت یک پروژه کاملا جدید و سالم در یک پوشه جداگانه (خارج از محیط گیت‌هاب)
          cd ..
          flutter create --project-name kudakeiran --platforms android clean_app
          
          # ۲. کپی کردن کدهای تو از پوشه گیت‌هاب به درون آن پروژه سالم
          # فایل های تو در پوشه $GITHUB_WORKSPACE هستند
          cp -r $GITHUB_WORKSPACE/lib/* clean_app/lib/
          cp $GITHUB_WORKSPACE/pubspec.yaml clean_app/pubspec.yaml
          
          # ۳. رفتن به پوشه جدید و انجام عملیات بیلد
          cd clean_app
          flutter pub get
          flutter build apk --release
          
          # ۴. کپی کردن فایل APK ساخته شده به مسیری که گیت‌هاب بتونه پیداش کنه
          mkdir -p $GITHUB_WORKSPACE/output
          cp build/app/outputs/flutter-apk/app-release.apk $GITHUB_WORKSPACE/output/
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KudakeIran-App
          path: output/app-release.apk
