name: KudakeIran Icon Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build with Custom Icon
        run: |
          # ۱. پاکسازی و ساخت پروژه استاندارد
          rm -rf /tmp/builder_app
          flutter create --project-name kudakeiran /tmp/builder_app
          cd /tmp/builder_app
          
          # ۲. جایگزینی کد و فایل ها
          rm -rf lib assets
          cp -r $GITHUB_WORKSPACE/lib .
          cp -r $GITHUB_WORKSPACE/assets .
          cp $GITHUB_WORKSPACE/pubspec.yaml .
          
          # ۳. نصب پکیج‌ها
          flutter pub get
          
          # ۴. ساخت خودکار آیکون از عکس آپلود شده (نقطه جادویی)
          dart run flutter_launcher_icons
          
          # ۵. بیلد نهایی APK
          flutter build apk --release

          # ۶. انتقال فایل به خروجی
          mkdir -p $GITHUB_WORKSPACE/output
          cp build/app/outputs/flutter-apk/app-release.apk $GITHUB_WORKSPACE/output/kudakeiran_branded.apk

      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: KudakeIran-Branded-App
          path: output/kudakeiran_branded.apk
