name: KudakeIran Pro Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enterprise Build Engine
        run: |
          # ۱. رفتن به محیط ایزوله
          cd /tmp
          
          # ۲. ساخت پروژه خام فلاتر
          flutter create --project-name kudakeiran --platforms android builder_app
          cd builder_app
          
          # ۳. اصلاح نسخه Kotlin برای سازگاری با پکیج های فاز ۸۵ (رفع ارور کد ۱)
          sed -i 's/ext.kotlin_version = .*/ext.kotlin_version = "1.9.0"/' android/build.gradle
          
          # ۴. جایگزینی کدهای اصلی استارتاپ
          rm -rf lib
          cp -r $GITHUB_WORKSPACE/lib .
          cp $GITHUB_WORKSPACE/pubspec.yaml .
          
          # ۵. بیلد APK با پاکسازی کش
          flutter pub get
          flutter build apk --release --split-per-abi

          # ۶. انتقال خروجی به فضای گیت‌هاب
          mkdir -p $GITHUB_WORKSPACE/build_output
          cp build/app/outputs/flutter-apk/app-release.apk $GITHUB_WORKSPACE/build_output/kudakeiran_v1_pro.apk

      - name: Upload Professional APK
        uses: actions/upload-artifact@v4
        with:
          name: KudakeIran_Enterprise_Release
          path: build_output/kudakeiran_v1_pro.apk
